#!/usr/bin/env python3

import os
import prettytable

content = os.listdir(".")

curpath = os.getcwd().split("/")    
curdir = curpath[len(curpath) - 1]

t = prettytable.PrettyTable([0, "\"%s\"" % curdir, "00 2a"])
t.align = "l"
t.border = False

for item in content:
    size = os.path.getsize("./%s" % item)
    ftype = 'USR'
    if os.access("./%s" % item, os.X_OK):
        ftype = 'PRG'
    if os.path.isdir("./%s" % item):
        ftype = 'DIR'
    t.add_row([size, "\"%s\"" % item, ftype])

print(t)


